spring.application.name=PTPro
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

server.port=8443
server.ssl.key-store=classpath:keystore/ptpro.p12
server.ssl.key-store-password=Test12345
server.ssl.keyStoreType=PKCS12
server.ssl.keyAlias=ptpro

client-id= PtPro
spring.security.oauth2.resourceserver.jwt.issuer-uri= http://localhost:9090/realms/PtPro
spring.security.oauth2.resourceserver.jwt.audiences= account


