INSERT INTO users (name, email, password)
VALUES ('Jan Jansen', 'jan.jansen@example.com', 'password123'),
       ('Piet Pieters', 'piet.pieters@example.com', 'secret456'),
       ('Anna de Vries', 'anna.vries@example.com', 'welcome789'),
       ('Tom Bakker', 'tom.bakker@example.com', 'qwerty123'),
       ('Lisa Meijer', 'lisa.meijer@example.com', 'abc12345'),
       ('Mark Smit', 'mark.smit@example.com', 'letmein99'),
       ('Eva de Boer', 'eva.boer@example.com', 'passwoord1'),
       ('Daan Visser', 'daan.visser@example.com', 'demo2024'),
       ('Sophie van Dijk', 'sophie.dijk@example.com', 'hello123'),
       ('Kevin de Groot', 'kevin.groot@example.com', 'testtest'),

       ('Nina Kuipers', 'nina.kuipers@example.com', 'admin321'),
       ('Lucas Hendriks', 'lucas.hendriks@example.com', 'welcome123'),
       ('Noah Mulder', 'noah.mulder@example.com', 'hunter22'),
       ('Emma Vos', 'emma.vos@example.com', 'mypassword'),
       ('Finn Peters', 'finn.peters@example.com', 'login2024'),
       ('Lotte Kramer', 'lotte.kramer@example.com', 'superpass'),
       ('Bram van Leeuwen', 'bram.leeuwen@example.com', 'java2025'),
       ('Mila Verhoeven', 'mila.verhoeven@example.com', 'springboot'),
       ('Jesse van Dam', 'jesse.dam@example.com', 'backend99'),
       ('Sara Kok', 'sara.kok@example.com', 'frontend88'),

       ('Ruben Scholten', 'ruben.scholten@example.com', 'secure123'),
       ('Iris de Lange', 'iris.lange@example.com', 'cloud456'),
       ('Thijs Willems', 'thijs.willems@example.com', 'docker789'),
       ('Laura van den Berg', 'laura.berg@example.com', 'kubernetes'),
       ('Sem Bos', 'sem.bos@example.com', 'microservice'),
       ('Roos Dekker', 'roos.dekker@example.com', 'react2024'),
       ('Timo van Vliet', 'timo.vliet@example.com', 'angular22'),
       ('Fleur Smits', 'fleur.smits@example.com', 'vuejs123'),
       ('Jasper van Rijn', 'jasper.rijn@example.com', 'node2025'),
       ('Kim Jacobs', 'kim.jacobs@example.com', 'python888'),

       ('Wouter Blom', 'wouter.blom@example.com', 'ai2026'),
       ('Floor Peeters', 'floor.peeters@example.com', 'mlmodel'),
       ('Rick Post', 'rick.post@example.com', 'datascience'),
       ('Yara Koster', 'yara.koster@example.com', 'bigdata'),
       ('Hugo Sanders', 'hugo.sanders@example.com', 'devops99'),
       ('Ilse van Houten', 'ilse.houten@example.com', 'linux777'),
       ('Sven Molenaar', 'sven.molenaar@example.com', 'network1'),
       ('Naomi Dijkstra', 'naomi.dijkstra@example.com', 'security22'),
       ('Jordy Maas', 'jordy.maas@example.com', 'api123'),
       ('Elise van Pelt', 'elise.pelt@example.com', 'graphql44');